# -*- coding: utf-8 -*-
"""Proyecto_final _1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gd10K87iqk0TpERFNtPdZ9qnNdSj3Orw
"""

# importar librerias
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Leer los datos del CSV
df = pd.read_csv('housing.csv')
print(df.head())

# valores nulos
datos_nulos = df.isnull().sum()
print(f'La cantidad de datos nulos es:\n{datos_nulos}')

# rellenar valores nulos SOLO en columnas numéricas
numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

print(df.isnull().sum())

# features / categorias
features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
            'total_bedrooms', 'population', 'households', 'median_income']

target = 'median_house_value'

# seleccionar X (variables independientes) e y (variable objetivo)
X = df[features]
y = df[target]

print("Características seleccionadas:")
display(df.head())

print("\nVariable objetivo:") # \n se usa para q aparezca una nueva linea separda a la salida anterior
display(df.head())

# separar las variables de Test y Train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear el modelo
model = LinearRegression()
model.fit(X_train, y_train)

# Realizar las predicciones
predict = model.predict(X_test)

# Calcular métricas de evaluacion
mae = mean_absolute_error(y_test, predict)
mse = mean_squared_error(y_test, predict)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, predict)

print("Métricas en conjunto de prueba:")
print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)